application: science-up
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app